# Network configuration
configure_network: false # Enable custom network configuration.
network_config: | # Content for /etc/network/interfaces.
  auto lo
  iface lo inet loopback

  iface ens18 inet manual

  auto vmbr0
  iface vmbr0 inet static
          address 192.168.1.83/24
          gateway 192.168.1.1
          bridge-ports ens18
          bridge-stp off
          bridge-fd 0
