# Users configuration
change_root_password: false # Enable changing the root password.
new_root_password: P@ssw0rd* # New root password.
system_user: localuser # Name of the non-root system user.
enable_system_user_password: true # Enable password authentication for the system user.
system_user_password: P@ssw0rd* # Password for the system user.
pub_keys_folder: pub_keys/ # Folder containing public SSH keys.
